# Extract, Transform and Load data

In [1]:
# Import dependencies
import pandas as pd
import numpy as np

### Extract the hate crime data

In [2]:
# Read the data into a Pandas DataFrame
hcrime_df = pd.read_excel('C:/Users/tnord/Downloads/hate_crimes_from_FBI.xlsx')
hcrime_df.head()

,incident_id,data_year,ori,pug_agency_name,pub_agency_unit,agency_type_name,state_abbr,state_name,division_name,region_name,...,offender_race,offender_ethnicity,victim_count,offense_name,total_individual_victims,location_name,bias_desc,victim_types,multiple_offense,multiple_bias
0,43,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,Not Specified,1,Aggravated Assault,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
1,44,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,Not Specified,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,S
2,45,1991,AR0600300,North Little Rock,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,Not Specified,2,Aggravated Assault;Murder and Nonnegligent Man...,2.0,Residence/Home,Anti-White,Individual,M,S
3,46,1991,AR0600300,North Little Rock,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,Not Specified,1,Intimidation,1.0,Residence/Home,Anti-White,Individual,S,S
4,47,1991,AR0670000,Sevier,NaN,County,AR,Arkansas,West South Central,South,...,White,Not Specified,1,Intimidation,1.0,School/College,Anti-Black or African American,Individual,S,S

In [3]:
hcrime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226328 entries, 0 to 226327
Data columns (total 28 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   incident_id                   226328 non-null  int64
 1   data_year                     226328 non-null  int64
 2   ori                           226328 non-null  object
 3   pug_agency_name               226328 non-null  object
 4   pub_agency_unit               6563 non-null    object
 5   agency_type_name              226328 non-null  object
 6   state_abbr                    226328 non-null  object
 7   state_name                    226328 non-null  object
 8   division_name                 226328 non-null  object
 9   region_name                   226328 non-null  object
 10  population_group_code         225924 non-null  object
 11  population_group_description  225924 non-null  object
 12  incident_date                 226328 non-null  datetime64[ns]
 13  adult_victim_count            58203 non-null   float64
 14  juvenile_victim_count         56331 non-null   float64
 15  total_offender_count          226328 non-null  int64
 16  adult_offender_count          53462 non-null   float64
 17  juvenile_offender_count       53455 non-null   float64
 18  offender_race                 226328 non-null  object
 19  offender_ethnicity            226328 non-null  object
 20  victim_count                  226328 non-null  int64
 21  offense_name                  226328 non-null  object
 22  total_individual_victims      222849 non-null  float64
 23  location_name                 226328 non-null  object
 24  bias_desc                     226328 non-null  object
 25  victim_types                  226328 non-null  object
 26  multiple_offense              226328 non-null  object
 27  multiple_bias                 226328 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(4), object(18)
memory usage: 48.3+ MB

In [4]:
#Dropping columns that will not be used
drop_col = ["pub_agency_unit","adult_victim_count","juvenile_victim_count","adult_offender_count","juvenile_offender_count"]
hcrime = hcrime_df.drop(columns= drop_col)
hcrime.head()

,incident_id,data_year,ori,pug_agency_name,agency_type_name,state_abbr,state_name,division_name,region_name,population_group_code,...,offender_race,offender_ethnicity,victim_count,offense_name,total_individual_victims,location_name,bias_desc,victim_types,multiple_offense,multiple_bias
0,43,1991,AR0350100,Pine Bluff,City,AR,Arkansas,West South Central,South,3,...,Black or African American,Not Specified,1,Aggravated Assault,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
1,44,1991,AR0350100,Pine Bluff,City,AR,Arkansas,West South Central,South,3,...,Black or African American,Not Specified,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,S
2,45,1991,AR0600300,North Little Rock,City,AR,Arkansas,West South Central,South,3,...,Black or African American,Not Specified,2,Aggravated Assault;Murder and Nonnegligent Man...,2.0,Residence/Home,Anti-White,Individual,M,S
3,46,1991,AR0600300,North Little Rock,City,AR,Arkansas,West South Central,South,3,...,Black or African American,Not Specified,1,Intimidation,1.0,Residence/Home,Anti-White,Individual,S,S
4,47,1991,AR0670000,Sevier,County,AR,Arkansas,West South Central,South,8D,...,White,Not Specified,1,Intimidation,1.0,School/College,Anti-Black or African American,Individual,S,S

In [5]:
hcrime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226328 entries, 0 to 226327
Data columns (total 23 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   incident_id                   226328 non-null  int64
 1   data_year                     226328 non-null  int64
 2   ori                           226328 non-null  object
 3   pug_agency_name               226328 non-null  object
 4   agency_type_name              226328 non-null  object
 5   state_abbr                    226328 non-null  object
 6   state_name                    226328 non-null  object
 7   division_name                 226328 non-null  object
 8   region_name                   226328 non-null  object
 9   population_group_code         225924 non-null  object
 10  population_group_description  225924 non-null  object
 11  incident_date                 226328 non-null  datetime64[ns]
 12  total_offender_count          226328 non-null  int64
 13  offender_race                 226328 non-null  object
 14  offender_ethnicity            226328 non-null  object
 15  victim_count                  226328 non-null  int64
 16  offense_name                  226328 non-null  object
 17  total_individual_victims      222849 non-null  float64
 18  location_name                 226328 non-null  object
 19  bias_desc                     226328 non-null  object
 20  victim_types                  226328 non-null  object
 21  multiple_offense              226328 non-null  object
 22  multiple_bias                 226328 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(17)
memory usage: 39.7+ MB

In [6]:
filtered_df = hcrime[hcrime["multiple_bias"]=="M"]
filtered_df["bias_desc"] =filtered_df["bias_desc"].str.split(';')
explode_df = filtered_df.explode("bias_desc", ignore_index=True)
explode_df.head(20)

C:\Users\tnord\AppData\Local\Temp\ipykernel_1332\2254811834.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["bias_desc"] =filtered_df["bias_desc"].str.split(';')

,incident_id,data_year,ori,pug_agency_name,agency_type_name,state_abbr,state_name,division_name,region_name,population_group_code,...,offender_race,offender_ethnicity,victim_count,offense_name,total_individual_victims,location_name,bias_desc,victim_types,multiple_offense,multiple_bias
0,662,1991,MA0091100,Cambridge,City,MA,Massachusetts,New England,Northeast,3,...,White,Not Specified,2,Robbery;Simple Assault,1.0,Other/Unknown,Anti-Gay (Male),Individual,M,M
1,662,1991,MA0091100,Cambridge,City,MA,Massachusetts,New England,Northeast,3,...,White,Not Specified,2,Robbery;Simple Assault,1.0,Other/Unknown,Anti-White,Individual,M,M
2,689,1991,MA0130100,Boston,City,MA,Massachusetts,New England,Northeast,1B,...,White,Not Specified,2,Intimidation;Robbery,1.0,Other/Unknown,Anti-Black or African American,Individual,M,M
3,689,1991,MA0130100,Boston,City,MA,Massachusetts,New England,Northeast,1B,...,White,Not Specified,2,Intimidation;Robbery,1.0,Other/Unknown,Anti-Jewish,Individual,M,M
4,696,1991,MA0130100,Boston,City,MA,Massachusetts,New England,Northeast,1B,...,White,Not Specified,2,Destruction/Damage/Vandalism of Property;Robbery,1.0,Other/Unknown,Anti-Black or African American,Individual,M,M
5,696,1991,MA0130100,Boston,City,MA,Massachusetts,New England,Northeast,1B,...,White,Not Specified,2,Destruction/Damage/Vandalism of Property;Robbery,1.0,Other/Unknown,Anti-Lesbian (Female),Individual,M,M
6,3259,1991,MA0130100,Boston,City,MA,Massachusetts,New England,Northeast,1B,...,White,Not Specified,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Other/Unknown,Anti-Gay (Male),Individual,M,M
7,3259,1991,MA0130100,Boston,City,MA,Massachusetts,New England,Northeast,1B,...,White,Not Specified,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Other/Unknown,Anti-White,Individual,M,M
8,3272,1991,MA0130100,Boston,City,MA,Massachusetts,New England,Northeast,1B,...,Asian,Not Specified,2,Intimidation;Simple Assault,1.0,Other/Unknown,Anti-Black or African American,Individual,M,M
9,3272,1991,MA0130100,Boston,City,MA,Massachusetts,New England,Northeast,1B,...,Asian,Not Specified,2,Intimidation;Simple Assault,1.0,Other/Unknown,Anti-Gay (Male),Individual,M,M
10,891,1991,MOSPD0000,St. Louis,City,MO,Missouri,West North Central,Midwest,1C,...,Multiple,Not Specified,2,Intimidation;Simple Assault,2.0,Service/Gas Station,Anti-Black or African American,Individual,M,M
11,891,1991,MOSPD0000,St. Louis,City,MO,Missouri,West North Central,Midwest,1C,...,Multiple,Not Specified,2,Intimidation;Simple Assault,2.0,Service/Gas Station,Anti-White,Individual,M,M
12,904,1991,MOSPD0000,St. Louis,City,MO,Missouri,West North Central,Midwest,1C,...,Multiple,Not Specified,15,Aggravated Assault;Intimidation;Murder and Non...,15.0,Parking/Drop Lot/Garage,Anti-Black or African American,Individual,M,M
13,904,1991,MOSPD0000,St. Louis,City,MO,Missouri,West North Central,Midwest,1C,...,Multiple,Not Specified,15,Aggravated Assault;Intimidation;Murder and Non...,15.0,Parking/Drop Lot/Garage,Anti-White,Individual,M,M
14,2539,1991,TXDPD0000,Dallas,City,TX,Texas,West South Central,South,1A,...,White,Not Specified,2,Intimidation;Simple Assault,2.0,Restaurant,Anti-Gay (Male),Individual,M,M
15,2539,1991,TXDPD0000,Dallas,City,TX,Texas,West South Central,South,1A,...,White,Not Specified,2,Intimidation;Simple Assault,2.0,Restaurant,Anti-Jewish,Individual,M,M
16,6243,1992,MOSPD0000,St. Louis,City,MO,Missouri,West North Central,Midwest,1C,...,Multiple,Not Specified,3,Aggravated Assault;Simple Assault,3.0,Highway/Road/Alley/Street/Sidewalk,Anti-Black or African American,Individual,M,M
17,6243,1992,MOSPD0000,St. Louis,City,MO,Missouri,West North Central,Midwest,1C,...,Multiple,Not Specified,3,Aggravated Assault;Simple Assault,3.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,M
18,11674,1993,CO0030000,Arapahoe,County,CO,Colorado,Mountain,West,9A,...,Black or African American,Not Specified,4,Intimidation;Simple Assault,4.0,Residence/Home,Anti-Black or African American,Individual,M,M
19,11674,1993,CO0030000,Arapahoe,County,CO,Colorado,Mountain,West,9A,...,Black or African American,Not Specified,4,Intimidation;Simple Assault,4.0,Residence/Home,Anti-White,Individual,M,M

In [7]:
explode_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2580 entries, 0 to 2579
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   incident_id                   2580 non-null   int64
 1   data_year                     2580 non-null   int64
 2   ori                           2580 non-null   object
 3   pug_agency_name               2580 non-null   object
 4   agency_type_name              2580 non-null   object
 5   state_abbr                    2580 non-null   object
 6   state_name                    2580 non-null   object
 7   division_name                 2580 non-null   object
 8   region_name                   2580 non-null   object
 9   population_group_code         2527 non-null   object
 10  population_group_description  2527 non-null   object
 11  incident_date                 2580 non-null   datetime64[ns]
 12  total_offender_count          2580 non-null   int64
 13  offender_race                 2580 non-null   object
 14  offender_ethnicity            2580 non-null   object
 15  victim_count                  2580 non-null   int64
 16  offense_name                  2580 non-null   object
 17  total_individual_victims      2183 non-null   float64
 18  location_name                 2580 non-null   object
 19  bias_desc                     2580 non-null   object
 20  victim_types                  2580 non-null   object
 21  multiple_offense              2580 non-null   object
 22  multiple_bias                 2580 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(4), object(17)
memory usage: 463.7+ KB

In [8]:
filtered_df2 = hcrime[hcrime["multiple_bias"]=="S"]
final_df = filtered_df2.merge(explode_df,how ='outer')

In [9]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 227709 entries, 0 to 227708
Data columns (total 23 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   incident_id                   227709 non-null  int64
 1   data_year                     227709 non-null  int64
 2   ori                           227709 non-null  object
 3   pug_agency_name               227709 non-null  object
 4   agency_type_name              227709 non-null  object
 5   state_abbr                    227709 non-null  object
 6   state_name                    227709 non-null  object
 7   division_name                 227709 non-null  object
 8   region_name                   227709 non-null  object
 9   population_group_code         227278 non-null  object
 10  population_group_description  227278 non-null  object
 11  incident_date                 227709 non-null  datetime64[ns]
 12  total_offender_count          227709 non-null  int64
 13  offender_race                 227709 non-null  object
 14  offender_ethnicity            227709 non-null  object
 15  victim_count                  227709 non-null  int64
 16  offense_name                  227709 non-null  object
 17  total_individual_victims      224008 non-null  float64
 18  location_name                 227709 non-null  object
 19  bias_desc                     227709 non-null  object
 20  victim_types                  227709 non-null  object
 21  multiple_offense              227709 non-null  object
 22  multiple_bias                 227709 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(17)
memory usage: 41.7+ MB

In [10]:
# Export the DataFrame as a CSV file. 
final_df.to_csv("resources/hate_crime.csv", index=False)

## Creating Categories for Biases

In [12]:
Sexual_orientation = ['Anti-Gay (Male)','Anti-Lesbian (Female)','Anti-Lesbian, Gay, Bisexual, or Transgender (Mixed Group)','Anti-Bisexual','Anti-Heterosexual']
Religion = ['Anti-Jewish','Anti-Arab', 'Anti-Protestant', 'Anti-Other Religion','Anti-Islamic (Muslim)', 'Anti-Catholic', 'Anti-Multiple Religions, Group','Anti-Atheism/Agnosticism','Anti-Buddhist', 'Anti-Sikh', 'Anti-Other Christian', 'Anti-Hindu','Anti-Eastern Orthodox (Russian, Greek, Other)',"Anti-Jehovah's Witness", 'Anti-Church of Jesus Christ']
Race_Ethnicity_Ancestry = ['Anti-Black or African American', 'Anti-White','Anti-Arab','Anti-Asian','Anti-Hispanic or Latino', 'Anti-Multiple Races, Group','Anti-Other Race/Ethnicity/Ancestry','Anti-American Indian or Alaska Native','Anti-Native Hawaiian or Other Pacific Islander']
Gender_identity = ['Anti-Gender Non-Conforming','Anti-Transgender']
Gender = ['Anti-Female','Anti-Male']
Disability = ['Anti-Physical Disability', 'Anti-Mental Disability']

# len(Sexual_orientation)
# len(Religion)
# len(Race_Ethnicity_Ancestry)
# len(Gender_identity)
# len(Gender)
# len(Disability)

In [13]:
data = {'category': "Sexual_orientation", 'bias': Sexual_orientation}
sexual_orientation_df = pd.DataFrame(data, columns = ['category','bias'])
sexual_orientation_df

             category                                               bias
0  Sexual_orientation                                    Anti-Gay (Male)
1  Sexual_orientation                              Anti-Lesbian (Female)
2  Sexual_orientation  Anti-Lesbian, Gay, Bisexual, or Transgender (M...
3  Sexual_orientation                                      Anti-Bisexual
4  Sexual_orientation                                  Anti-Heterosexual

In [14]:
data = {'category': "Religion", 'bias': Religion}
Religion_df = pd.DataFrame(data, columns = ['category','bias'])
Religion_df

    category                                           bias
0   Religion                                    Anti-Jewish
1   Religion                                      Anti-Arab
2   Religion                                Anti-Protestant
3   Religion                            Anti-Other Religion
4   Religion                          Anti-Islamic (Muslim)
5   Religion                                  Anti-Catholic
6   Religion                 Anti-Multiple Religions, Group
7   Religion                       Anti-Atheism/Agnosticism
8   Religion                                  Anti-Buddhist
9   Religion                                      Anti-Sikh
10  Religion                           Anti-Other Christian
11  Religion                                     Anti-Hindu
12  Religion  Anti-Eastern Orthodox (Russian, Greek, Other)
13  Religion                         Anti-Jehovah's Witness
14  Religion                    Anti-Church of Jesus Christ

In [15]:
data = {'category': "Race_Ethnicity_Ancestry", 'bias': Race_Ethnicity_Ancestry}
Race_Ethnicity_Ancestry_df = pd.DataFrame(data, columns = ['category','bias'])
Race_Ethnicity_Ancestry_df

                  category                                            bias
0  Race_Ethnicity_Ancestry                  Anti-Black or African American
1  Race_Ethnicity_Ancestry                                      Anti-White
2  Race_Ethnicity_Ancestry                                       Anti-Arab
3  Race_Ethnicity_Ancestry                                      Anti-Asian
4  Race_Ethnicity_Ancestry                         Anti-Hispanic or Latino
5  Race_Ethnicity_Ancestry                      Anti-Multiple Races, Group
6  Race_Ethnicity_Ancestry              Anti-Other Race/Ethnicity/Ancestry
7  Race_Ethnicity_Ancestry           Anti-American Indian or Alaska Native
8  Race_Ethnicity_Ancestry  Anti-Native Hawaiian or Other Pacific Islander

In [16]:
data = {'category': "Gender_identity", 'bias': Gender_identity}
Gender_identity_df = pd.DataFrame(data, columns = ['category','bias'])
Gender_identity_df

          category                        bias
0  Gender_identity  Anti-Gender Non-Conforming
1  Gender_identity            Anti-Transgender

In [17]:
data = {'category': "Gender", 'bias': Gender}
Gender_df = pd.DataFrame(data, columns = ['category','bias'])
Gender_df

  category         bias
0   Gender  Anti-Female
1   Gender    Anti-Male

In [18]:
data = {'category': "Disability", 'bias': Disability}
Disability_df = pd.DataFrame(data, columns = ['category','bias'])
Disability_df

     category                      bias
0  Disability  Anti-Physical Disability
1  Disability    Anti-Mental Disability

In [19]:
bias_df = sexual_orientation_df.merge(Religion_df,how ='outer').merge(Race_Ethnicity_Ancestry_df, how ="outer").merge(Gender_identity_df, how ="outer").merge(Gender_df, how ="outer").merge(Disability_df, how ="outer")

In [43]:
categories = bias_df["category"].unique().tolist()
# Create dataframe for category
category_df = pd.DataFrame(categories, columns=['category'])
category_df.index.name = 'category_id'
category_df

                            category
category_id
0                 Sexual_orientation
1                           Religion
2            Race_Ethnicity_Ancestry
3                    Gender_identity
4                             Gender
5                         Disability

In [57]:
#Saving to csv file
category_df.to_csv("C:/Users/tnord/OneDrive/Desktop/Bootcamp_Projects/Project-3/etl/data/bias_categories.csv", index=True)

## Biases table

In [49]:
# Read the data into a Pandas DataFrame
categories= pd.read_csv('resources/bias_categories.csv')
categories

   category_id                 category
0            0       Sexual_orientation
1            1                 Religion
2            2  Race_Ethnicity_Ancestry
3            3          Gender_identity
4            4                   Gender
5            5               Disability

In [21]:
bias = final_df["bias_desc"].unique().tolist()

In [22]:
# Create dataframe for bias
biases_df = pd.DataFrame(bias, columns=['bias_desc'])
biases_df.index.name = 'bias_id'
biases_df

                                                 bias_desc
bias_id
0                           Anti-Black or African American
1                                               Anti-White
2                                              Anti-Jewish
3                                                Anti-Arab
4                                          Anti-Protestant
5                                      Anti-Other Religion
6                                    Anti-Islamic (Muslim)
7                                          Anti-Gay (Male)
8                                               Anti-Asian
9                                            Anti-Catholic
10                          Anti-Multiple Religions, Group
11                                 Anti-Hispanic or Latino
12                              Anti-Multiple Races, Group
13                                   Anti-Lesbian (Female)
14                      Anti-Other Race/Ethnicity/Ancestry
15                                       Anti-Heterosexual
16       Anti-Lesbian, Gay, Bisexual, or Transgender (M...
17                   Anti-American Indian or Alaska Native
18                                Anti-Atheism/Agnosticism
19                                           Anti-Bisexual
20                                Anti-Physical Disability
21                                  Anti-Mental Disability
22                              Anti-Gender Non-Conforming
23                                             Anti-Female
24                                        Anti-Transgender
25          Anti-Native Hawaiian or Other Pacific Islander
26                                               Anti-Male
27                                  Anti-Jehovah's Witness
28                             Anti-Church of Jesus Christ
29                                           Anti-Buddhist
30                                               Anti-Sikh
31                                    Anti-Other Christian
32                                              Anti-Hindu
33           Anti-Eastern Orthodox (Russian, Greek, Other)
34               Unknown (offender's motivation not known)

In [51]:
# Merge dataframes to create bias table with bias_id, bias, category_id
bias = biases_df.merge( bias_df,left_on  = "bias_desc",right_on ="bias", how = 'right').merge(categories,on  = "category", how = 'right')
bias = bias[['bias_desc','category_id']]
bias.index.name = 'bias_id'
bias

                                                 bias_desc  category_id
bias_id
0                                          Anti-Gay (Male)            0
1                                    Anti-Lesbian (Female)            0
2        Anti-Lesbian, Gay, Bisexual, or Transgender (M...            0
3                                            Anti-Bisexual            0
4                                        Anti-Heterosexual            0
5                                              Anti-Jewish            1
6                                                Anti-Arab            1
7                                          Anti-Protestant            1
8                                      Anti-Other Religion            1
9                                    Anti-Islamic (Muslim)            1
10                                           Anti-Catholic            1
11                          Anti-Multiple Religions, Group            1
12                                Anti-Atheism/Agnosticism            1
13                                           Anti-Buddhist            1
14                                               Anti-Sikh            1
15                                    Anti-Other Christian            1
16                                              Anti-Hindu            1
17           Anti-Eastern Orthodox (Russian, Greek, Other)            1
18                                  Anti-Jehovah's Witness            1
19                             Anti-Church of Jesus Christ            1
20                          Anti-Black or African American            2
21                                              Anti-White            2
22                                               Anti-Arab            2
23                                              Anti-Asian            2
24                                 Anti-Hispanic or Latino            2
25                              Anti-Multiple Races, Group            2
26                      Anti-Other Race/Ethnicity/Ancestry            2
27                   Anti-American Indian or Alaska Native            2
28          Anti-Native Hawaiian or Other Pacific Islander            2
29                              Anti-Gender Non-Conforming            3
30                                        Anti-Transgender            3
31                                             Anti-Female            4
32                                               Anti-Male            4
33                                Anti-Physical Disability            5
34                                  Anti-Mental Disability            5

In [58]:
#Saving to csv file
bias.to_csv("C:/Users/tnord/OneDrive/Desktop/Bootcamp_Projects/Project-3/etl/data/bias.csv", index=True)

### Incidents and locations

In [25]:
hcrime_df["location_name"] =hcrime_df["location_name"].str.split(';')
explode_df = hcrime_df.explode("location_name", ignore_index=True)

In [26]:
loc_df = explode_df["location_name"].unique()
# Create dataframe for bias
loc_df = pd.DataFrame(loc_df, columns=['location_name'])
loc_df.index.name = 'location_id'
loc_df

                                             location_name
location_id
0                                           Residence/Home
1                       Highway/Road/Alley/Street/Sidewalk
2                                           School/College
3                                      Service/Gas Station
4                                      Grocery/Supermarket
5                           Church/Synagogue/Temple/Mosque
6                                            Other/Unknown
7                               Commercial/Office Building
8                                   Air/Bus/Train Terminal
9                                  Parking/Drop Lot/Garage
10                                        Hotel/Motel/Etc.
11                                              Restaurant
12                                       Convenience Store
13                               Department/Discount Store
14                                           Bar/Nightclub
15                                         Specialty Store
16                     Drug Store/Doctor's Office/Hospital
17                              Government/Public Building
18                                     Lake/Waterway/Beach
19           Jail/Prison/Penitentiary/Corrections Facility
20                                             Field/Woods
21                                            Liquor Store
22                                   Bank/Savings and Loan
23                                 Rental Storage Facility
24                                       Construction Site
25                               School-College/University
26                             School-Elementary/Secondary
27                                         Industrial Site
28                     Gambling Facility/Casino/Race Track
29                                           Shopping Mall
30                                         Camp/Campground
31                                         Park/Playground
32                                            Tribal Lands
33                      Arena/Stadium/Fairgrounds/Coliseum
34                                  ATM Separate from Bank
35                                           Farm Facility
36                                          Amusement Park
37                                        Daycare Facility
38                                Auto Dealership New/Used
39                                               Rest Area
40                           Abandoned/Condemned Structure
41                                Shelter-Mission/Homeless
42                       Dock/Wharf/Freight/Modal Terminal
43                                        Community Center
44                                   Military Installation
45                                              Cyberspace

In [59]:
#Saving to csv file
loc_df.to_csv("C:/Users/tnord/OneDrive/Desktop/Bootcamp_Projects/Project-3/etl/data/location.csv", index=True)

## Incident locations

In [28]:
# Read the data into a Pandas DataFrame
location_df = pd.read_csv('resources/location.csv')
location_df.head()

   location_id                       location_name
0            0                      Residence/Home
1            1  Highway/Road/Alley/Street/Sidewalk
2            2                      School/College
3            3                 Service/Gas Station
4            4                 Grocery/Supermarket

In [29]:
inci_df = explode_df[['incident_id','location_name']]

In [30]:
incident_locations = inci_df.merge( location_df,on  = "location_name", how = 'right')

In [31]:
incident_locations = incident_locations[["incident_id","location_id"]]
incident_locations.head()

   incident_id  location_id
0           43            0
1           45            0
2           46            0
3         3021            0
4            2            0

In [60]:
#Saving to csv file
incident_locations.to_csv("C:/Users/tnord/OneDrive/Desktop/Bootcamp_Projects/Project-3/etl/data/incident_locations.csv", index=False)

## Incident Biases

In [33]:
# Read the data into a Pandas DataFrame
bias = pd.read_csv('resources/bias.csv')
bias.head()

   bias_id                       bias_desc
0        0  Anti-Black or African American
1        1                      Anti-White
2        2                     Anti-Jewish
3        3                       Anti-Arab
4        4                 Anti-Protestant

In [34]:
incident = final_df[['incident_id','bias_desc']]
incident_biases = incident.merge( bias, on  = "bias_desc", how = 'right')
incident_biases = incident_biases[["incident_id","bias_id"]]
incident_biases.head()

   incident_id  bias_id
0           43        0
1           47        0
2         3015        0
3            2        0
4            5        0

In [61]:
#Saving to csv file
incident_biases.to_csv("C:/Users/tnord/OneDrive/Desktop/Bootcamp_Projects/Project-3/etl/data/incident_biases.csv", index=False)