In [1]:
import pandas as pd

In [5]:
raw_data = pd.read_csv("resources/fbi_hate_crime_data.csv")
raw_data.head()

,incident_id,data_year,ori,pug_agency_name,pub_agency_unit,agency_type_name,state_abbr,state_name,division_name,region_name,...,offender_race,offender_ethnicity,victim_count,offense_name,total_individual_victims,location_name,bias_desc,victim_types,multiple_offense,multiple_bias
0,43,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,Not Specified,1,Aggravated Assault,1.0,Residence/Home,Anti-Black or African American,Individual,S,S
1,44,1991,AR0350100,Pine Bluff,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,Not Specified,2,Aggravated Assault;Destruction/Damage/Vandalis...,1.0,Highway/Road/Alley/Street/Sidewalk,Anti-White,Individual,M,S
2,45,1991,AR0600300,North Little Rock,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,Not Specified,2,Aggravated Assault;Murder and Nonnegligent Man...,2.0,Residence/Home,Anti-White,Individual,M,S
3,46,1991,AR0600300,North Little Rock,NaN,City,AR,Arkansas,West South Central,South,...,Black or African American,Not Specified,1,Intimidation,1.0,Residence/Home,Anti-White,Individual,S,S
4,47,1991,AR0670000,Sevier,NaN,County,AR,Arkansas,West South Central,South,...,White,Not Specified,1,Intimidation,1.0,School/College,Anti-Black or African American,Individual,S,S

In [15]:
year_df = raw_data[raw_data['data_year'] > 2008].reset_index(drop=True)
year_df.keys()

Index(['incident_id', 'data_year', 'ori', 'pug_agency_name', 'pub_agency_unit',
       'agency_type_name', 'state_abbr', 'state_name', 'division_name',
       'region_name', 'population_group_code', 'population_group_description',
       'incident_date', 'adult_victim_count', 'juvenile_victim_count',
       'total_offender_count', 'adult_offender_count',
       'juvenile_offender_count', 'offender_race', 'offender_ethnicity',
       'victim_count', 'offense_name', 'total_individual_victims',
       'location_name', 'bias_desc', 'victim_types', 'multiple_offense',
       'multiple_bias'],
      dtype='object')

In [16]:
columns_to_drop = ['ori', 'pug_agency_name','pub_agency_unit',
       'agency_type_name','division_name',
       'region_name', 
       'incident_date', 
       'location_name']
drop1_df = year_df.drop(columns=columns_to_drop)
drop1_df.head()

,incident_id,data_year,state_abbr,state_name,population_group_code,population_group_description,adult_victim_count,juvenile_victim_count,total_offender_count,adult_offender_count,juvenile_offender_count,offender_race,offender_ethnicity,victim_count,offense_name,total_individual_victims,bias_desc,victim_types,multiple_offense,multiple_bias
0,141003,2009,AK,Alaska,1C,"Cities from 250,000 thru 499,999",NaN,NaN,1,NaN,NaN,White,Not Specified,1,Simple Assault,1.0,Anti-American Indian or Alaska Native,Individual,S,S
1,141004,2009,AK,Alaska,1C,"Cities from 250,000 thru 499,999",NaN,NaN,0,NaN,NaN,Unknown,Not Specified,1,Intimidation,1.0,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",Individual,S,S
2,141005,2009,AK,Alaska,1C,"Cities from 250,000 thru 499,999",NaN,NaN,2,NaN,NaN,White,Not Specified,1,Robbery,1.0,Anti-American Indian or Alaska Native,Individual,S,S
3,141006,2009,AK,Alaska,1C,"Cities from 250,000 thru 499,999",NaN,NaN,3,NaN,NaN,Multiple,Not Specified,4,Aggravated Assault,4.0,Anti-American Indian or Alaska Native,Individual,S,S
4,141007,2009,AK,Alaska,1C,"Cities from 250,000 thru 499,999",NaN,NaN,2,NaN,NaN,Asian,Not Specified,1,Robbery,1.0,Anti-American Indian or Alaska Native,Individual,S,S

In [17]:
pop_code = drop1_df.population_group_code.unique()
pop_code

array(['1C', '6', '3', '2', '7', '5', '4', '8D', '8C', '9B', '9C', '1A',
       '9A', '1B', '8B', '9D', '8A', '8E', '9E', '0', nan], dtype=object)

In [18]:
pop_description = drop1_df.population_group_description.unique()
pop_description

array(['Cities from 250,000 thru 499,999', 'Cities from 2,500 thru 9,999',
       'Cities from 50,000 thru 99,999',
       'Cities from 100,000 thru 249,999', 'Cities under 2,500',
       'Cities from 10,000 thru 24,999', 'Cities from 25,000 thru 49,999',
       'Non-MSA counties under 10,000',
       'Non-MSA counties from 10,000 thru 24,999',
       'MSA counties from 25,000 thru 99,999',
       'MSA counties from 10,000 thru 24,999', 'Cities 1,000,000 or over',
       'MSA counties 100,000 or over', 'Cities from 500,000 thru 999,999',
       'Non-MSA counties from 25,000 thru 99,999',
       'MSA counties under 10,000', 'Non-MSA counties 100,000 or over',
       'Non-MSA State Police', 'MSA State Police',
       'Possessions (Puerto Rico, Guam, Virgin Islands, and American Samoa)',
       nan], dtype=object)

In [19]:
multiple_code = drop1_df.multiple_bias.unique()
multiple_code

array(['S', 'M'], dtype=object)

In [21]:
columns_to_drop = ['population_group_code', 'population_group_description', 'adult_victim_count', 'juvenile_victim_count',      
         'adult_offender_count',
       'juvenile_offender_count']
drop2_df = drop1_df.drop(columns=columns_to_drop)
drop2_df.keys()

Index(['incident_id', 'data_year', 'state_abbr', 'state_name',
       'total_offender_count', 'offender_race', 'offender_ethnicity',
       'victim_count', 'offense_name', 'total_individual_victims', 'bias_desc',
       'victim_types', 'multiple_offense', 'multiple_bias'],
      dtype='object')

In [22]:
target_value = 'S'
single_bias_df = drop2_df[drop2_df['multiple_bias'].str.contains(target_value, case=False)]
single_bias_df.head()

,incident_id,data_year,state_abbr,state_name,total_offender_count,offender_race,offender_ethnicity,victim_count,offense_name,total_individual_victims,bias_desc,victim_types,multiple_offense,multiple_bias
0,141003,2009,AK,Alaska,1,White,Not Specified,1,Simple Assault,1.0,Anti-American Indian or Alaska Native,Individual,S,S
1,141004,2009,AK,Alaska,0,Unknown,Not Specified,1,Intimidation,1.0,"Anti-Lesbian, Gay, Bisexual, or Transgender (M...",Individual,S,S
2,141005,2009,AK,Alaska,2,White,Not Specified,1,Robbery,1.0,Anti-American Indian or Alaska Native,Individual,S,S
3,141006,2009,AK,Alaska,3,Multiple,Not Specified,4,Aggravated Assault,4.0,Anti-American Indian or Alaska Native,Individual,S,S
4,141007,2009,AK,Alaska,2,Asian,Not Specified,1,Robbery,1.0,Anti-American Indian or Alaska Native,Individual,S,S

In [23]:
target_value = 'M'
multi_bias_df = drop2_df[drop2_df['multiple_bias'].str.contains(target_value, case=False)]
multi_bias_df.head()

,incident_id,data_year,state_abbr,state_name,total_offender_count,offender_race,offender_ethnicity,victim_count,offense_name,total_individual_victims,bias_desc,victim_types,multiple_offense,multiple_bias
780,137625,2009,CA,California,0,Unknown,Not Specified,2,Destruction/Damage/Vandalism of Property;Intim...,1.0,Anti-Black or African American;Anti-Multiple R...,Individual,M,M
1465,141419,2009,CO,Colorado,1,White,Not Specified,2,Burglary/Breaking & Entering;Destruction/Damag...,0.0,Anti-Hispanic or Latino;Anti-Other Race/Ethnic...,Business,M,M
1616,137918,2009,CT,Connecticut,1,White,Not Specified,2,Destruction/Damage/Vandalism of Property;Intim...,2.0,Anti-Gay (Male);Anti-Other Race/Ethnicity/Ance...,Individual,M,M
2353,138428,2009,KY,Kentucky,1,White,Not Specified,4,Intimidation;Simple Assault,4.0,Anti-Asian;Anti-Black or African American,Individual,M,M
5618,140343,2009,SC,South Carolina,1,Unknown,Not Specified,2,Burglary/Breaking & Entering;Destruction/Damag...,2.0,"Anti-Gay (Male);Anti-Lesbian, Gay, Bisexual, o...",Individual,M,M

In [24]:
drop2_df.to_csv('main_incidents', index=False)